# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xTcjFoQ7E-Z9Y2bz0D42mibRAjtZoliC
"""

import datetime                            
import pymongo
from pymongo import MongoClient
import pandas as pd

! pip install streamlit

import streamlit as st

Aditi_test = MongoClient("mongodb+srv://candidate:candidate2022@cluster0.p8u2o.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
Aditi_test['master-catalogue']['test-temp'].find_one({})
